var textStrings = {
  niceHat: "OOH NICE HAT",
  outtaHere: "yeah get on outta here",
  getARoom: "GROSS, GO GET A ROOM",
  notCoolAnymore: "never mind, hats are not cool anymore",
  tvOnTv: "A TV... ON TV!",
  cricky: "LIL CRICKY <3",
  tooManyCrickets: "okay that is too many crickets",
  normalPeep: "just a normal peep",
  normalPeeps: "just some normal peeps",
  wowNothing: "WOW, IT IS NOTHING",
  crazySquareAttacks: "CRAZED SQUARE ATTACKS",
  justMissed: "oooooh just missed it",
  somethingInteresting: "(you have to catch them doing something interesting)",
  whoIsScreaming: "(you have to catch who is screaming at them)",
  circleFearsSquares: "CIRCLE FEARS SQUARES",
  whoScaresThem: "(you also have to catch who scares them)",
  squaresSnubCircles: "SQUARES SNUB CIRCLES",
  everyoneHates: "EVERYONE HATES EVERYONE",
  almostEveryoneHates: "ALMOST EVERYONE HATES EVERYONE...",
  squaresHateCircles: "SQUARES HATE CIRCLES",
  circlesHateSquares: "CIRCLES HATE SQUARES",
  areTheyYelling: "(you have to catch them yelling at each other)",
  nerdsNow: "what are these nerds doing now",
  schockedPeep: "why is this peep shocked?",
  whatever: "whatever",
  ellipsis: ". . .",
  coolNoMore: "hats are not cool anymore, did you not hear?",
  beScared: "BE SCARED. BE ANGRY.",
  manifesto: [
    "who tunes in to watch people get along?",
    "peace is boring. violence goes viral.",
    "and every story needs a conflict, so...",
    "GIVE THE AUDIENCE WHAT THEY WANT."
  ],
  playingTime: "playing time: 5 minutes",
  warning: "warning: the following program\ncontains snobbery,\nrudeness, and mass murder.\nviewer discretion is advised.",
  pointAndClick: "POINT AND CLICK",
  chyronNothing: "WOW, IT IS NOTHING",
  WBWWB: "We become what we behold.",
  WSOTATOTSU: "We shape our tools and then our tools shape us.",
  MarshallMcLuhan: "Marshall McLuhan",
  misatrributed: "(misattributed)"
};
