(() => {
  const modelRanges = {
    Automatic_device_bridge: [1452, 2712],
    Automatic_device_framework: [6750, 8154],
    Balance_bridge: [23352, 6942],
    Balance_jewel: [37338, 732],
    Balance_safety: [38826, 1224],
    Balance_shaft_end: [41298, 687],
    Balance_spring_base: [42141, 564],
    Balance_wheel: [43329, 3006],
    Barrel_arbor: [49353, 3483],
    Barrel_bridge: [56388, 8646],
    Barrel_lid: [83178, 3036],
    Barrel_main: [89250, 7020],
    Cannon_pinion: [102750, 1752],
    Cannon_wheel: [105942, 1242],
    Click_spring: [107934, 1140],
    Click: [110256, 672],
    Corrector_lever: [111618, 1356],
    Crown_wheel: [114396, 1620],
    Crown: [117096, 1200],
    Cube: [119748, 36],
    Cylinder: [119856, 540],
    Date_corrector: [126195, 2220],
    Date_indicator_spring: [130731, 1245],
    Date_jumper_plate: [133752, 3594],
    Date_jumper: [140982, 1590],
    Date_ring: [143988, 3312],
    Dial: [151356, 1524],
    Escape_wheel: [154440, 4938],
    Fourth_wheel: [164976, 2064],
    Hour_hand: [168660, 744],
    Hour_wheel: [170196, 1518],
    Jewel_bearing: [173064, 666],
    Jewel_pretty: [174396, 3654],
    Lower_index: [178050, 1080],
    Mainplate: [180282, 28308],
    Mainspring_base: [237546, 1350],
    Minute_hand: [240834, 588],
    Minute_train_bridge: [242058, 1956],
    Pallet_bridge: [246084, 4236],
    Pallet_fork_horn: [254610, 1134],
    Pallet_fork: [256914, 1848],
    Pallet_jewel_1: [260742, 48],
    Pallet_jewel_2: [260880, 36],
    Pinion_center: [260988, 546],
    Ratchet_wheel: [261966, 1128],
    Reversing_wheel_bottom: [263166, 5838],
    Reversing_wheel_cut: [274530, 4026],
    Reversing_wheel_lever: [283170, 960],
    Reversing_wheel_top: [285102, 4302],
    Screw_head: [294126, 390],
    Second_hand: [294942, 372],
    Second_wheel: [295734, 2262],
    Setting_lever_jumper: [299742, 4728],
    Setting_lever: [308694, 756],
    Shock_base: [313128, 3918],
    Shock_center: [322317, 1620],
    Shock_jewel: [325557, 648],
    Shock_spring: [326649, 1224],
    Sliding_pinion: [328881, 1854],
    Stop_lever: [333003, 990],
    Stud_base: [335025, 1002],
    Stud: [337101, 1476],
    Third_wheel: [339651, 2112],
    Train_bridge: [343419, 6312],
    Upper_index: [356301, 1842],
    Weight: [360093, 4440],
    Winding_pinion: [369051, 2268],
    Winding_stem: [373155, 897],
    Yoke: [375186, 1512],
  };

  const lessons = [
    { id: "power", label: "Power", title: "Store energy", problem: "How can a watch keep running after it leaves your hand?", mechanism: "Winding coils a spring inside a toothed barrel.", result: "The barrel releases a slow, sustained turning force.", primaryPartId: "mainspring" },
    { id: "gears", label: "Gear Train", title: "Trade torque for speed", problem: "How does the barrel's slow rotation become useful motion?", mechanism: "Compound wheels and pinions increase speed at each mesh.", result: "The fourth wheel turns once per minute and carries the seconds display.", primaryPartId: "center-wheel" },
    { id: "escapement", label: "Escapement", title: "Release one tooth", problem: "What stops the gear train from emptying the mainspring at once?", mechanism: "The pallet fork alternately locks and releases the escape wheel.", result: "Stored torque leaves the train as a sequence of small impulses.", primaryPartId: "pallet-fork" },
    { id: "balance", label: "Balance", title: "Make a steady beat", problem: "How can those impulses become equal units of time?", mechanism: "The hairspring returns the balance wheel through a repeatable oscillation.", result: "Each swing unlocks the escapement and sets the watch's rate.", primaryPartId: "balance-wheel" },
    { id: "mainplate", label: "Mainplate", title: "Hold every pivot", problem: "How can dozens of tiny wheels remain aligned under load?", mechanism: "The mainplate, jewels, and bridges fix each arbor on a low-friction axis.", result: "The train stays meshed while every wheel remains free to turn.", primaryPartId: "mainplate" },
    { id: "click", label: "Click", title: "Keep winding one-way", problem: "What prevents the wound spring from driving the crown backward?", mechanism: "The click rides over ratchet teeth during winding and blocks reverse rotation.", result: "Energy enters the barrel but cannot escape through the winding train.", primaryPartId: "click" },
    { id: "motion-works", label: "Motion Works", title: "Divide time for display", problem: "How does one regulated train drive minutes, hours, and the date?", mechanism: "A friction-fit cannon pinion and reduction wheels split the rotation into useful ratios.", result: "The hands remain synchronized while the calendar advances in steps.", primaryPartId: "cannon-pinion" },
    { id: "keyless-works", label: "Keyless Works", title: "Give the crown three jobs", problem: "How can one control wind, correct the date, and set the hands?", mechanism: "Pulling the stem moves a yoke that redirects the sliding pinion.", result: "Each crown position engages a different mechanical path.", primaryPartId: "sliding-pinion" },
    { id: "automatic-winding", label: "Automatic Winding", title: "Harvest wrist motion", problem: "How can daily movement replenish the mainspring automatically?", mechanism: "A weighted rotor and two reversers rectify motion from either direction.", result: "The reduction train delivers one-way winding torque to the barrel.", primaryPartId: "rotor" },
    { id: "the-size-of-it-all", label: "Physical Scale", title: "Protect a tiny machine", problem: "How does the complete mechanism survive while remaining readable?", mechanism: "The crystal closes the dial side within a case only millimeters thick.", result: "The moving display remains visible while the calibre stays protected.", primaryPartId: "crystal" },
  ];

  const archivedPhase = -37.2587 * Math.PI / 180;

  const parts = [
    { id: "case", name: "Case ring", system: "Casing", role: "Protects the movement and establishes the outer assembly datum.", lessonId: "mainplate", lessonLabel: "Assembly", color: "#64717d", kind: "case", home: [0, 0, 0], explode: [0, 0, 17] },
    { id: "crystal", name: "Sapphire crystal", system: "Casing", role: "Closes the dial side while leaving the display visible.", lessonId: "the-size-of-it-all", lessonLabel: "Physical Scale", color: "#b9e6ef", kind: "crystal", transparent: true, home: [0, 0, 3.1], explode: [0, 0, 22] },
    { id: "caseback", name: "Display caseback", system: "Casing", role: "Closes the movement side and exposes the automatic winding assembly.", lessonId: "automatic-winding", lessonLabel: "Automatic Winding", color: "#77838f", kind: "caseback", home: [0, 0, -3.1], explode: [0, 0, -21] },
    { id: "dial", name: "Dial and markers", system: "Display", role: "Provides the reference scale read by the hands; sixty generated markers complete the source dial mesh.", lessonId: "motion-works", lessonLabel: "Motion Works", color: "#d8d3c8", kind: "dial", source: ["Dial"], home: [0, 0, 1.9], explode: [0, 0, 14] },
    { id: "date-ring", name: "Date ring", system: "Calendar", role: "Advances one indexed position at midnight to expose the next date through the dial aperture.", lessonId: "motion-works", lessonLabel: "Motion Works", color: "#ebe8de", source: ["Date_ring"], home: [0, 0, 1.45], explode: [0, 0, 11], animation: "date" },
    { id: "hour-hand", name: "Hour hand", system: "Display", role: "Turns once every twelve hours from the motion works reduction train.", lessonId: "motion-works", lessonLabel: "Motion Works", color: "#d6dce2", source: ["Hour_hand"], sourceTransforms: { Hour_hand: { position: [-3, 0, 0], rotation: [0, 0, Math.PI] } }, home: [0, 0, 2.25], explode: [-1.2, 0, 15], animation: "hour" },
    { id: "minute-hand", name: "Minute hand", system: "Display", role: "Tracks the cannon pinion and completes one revolution per hour.", lessonId: "motion-works", lessonLabel: "Motion Works", color: "#eef1f3", source: ["Minute_hand"], sourceTransforms: { Minute_hand: { position: [-3.8, 0, 0], rotation: [0, 0, Math.PI] } }, home: [0, 0, 2.5], explode: [0, 0, 17], animation: "minute" },
    { id: "second-hand", name: "Seconds hand", system: "Display", role: "Couples to the fourth wheel and makes the escapement's regulated release visible.", lessonId: "gears", lessonLabel: "Gear Train", color: "#c54b4b", source: ["Second_hand"], sourceTransforms: { Second_hand: { position: [2.497962, 4.560723, 0], rotation: [0, 0, 1.07] } }, home: [0, 0, 2.75], explode: [1.2, 0, 19], animation: "seconds" },
    { id: "mainplate", name: "Mainplate", system: "Structure", role: "The movement chassis from which pivots, jewels, bridges, and keyless works register.", lessonId: "mainplate", lessonLabel: "Mainplate", color: "#aeb5bb", source: ["Mainplate"], home: [0, 0, 0], explode: [0, 0, 0] },
    { id: "barrel-drum", name: "Mainspring barrel", system: "Power", role: "Contains the mainspring and releases stored torque through its toothed rim.", lessonId: "power", lessonLabel: "Power", color: "#d8a657", source: ["Barrel_main"], sourceTransforms: { Barrel_main: { position: [0, 0, 0], rotation: [Math.PI, 0, 0.002] } }, home: [5.78, 2.89, 0.45], explode: [3, 1.8, 5], animation: "barrel" },
    { id: "barrel-lid", name: "Barrel lid", system: "Power", role: "Captures the mainspring inside the rotating barrel drum.", lessonId: "power", lessonLabel: "Power", color: "#c99b57", source: ["Barrel_lid"], sourceTransforms: { Barrel_lid: { position: [-0.000003, 0.0015, 0], rotation: [Math.PI, 0, 0.002] } }, home: [5.78, 2.89, 0.68], explode: [3.4, 2.1, 7], animation: "barrel" },
    { id: "barrel-arbor", name: "Barrel arbor", system: "Power", role: "Anchors the mainspring's inner end and accepts winding torque from the ratchet wheel.", lessonId: "power", lessonLabel: "Power", color: "#d4b06c", source: ["Barrel_arbor"], sourceTransforms: { Barrel_arbor: { position: [0.03, -0.03, 0], rotation: [Math.PI, 0, 0] } }, home: [5.78, 2.89, 0.2], explode: [3.8, 2.4, 9], animation: "barrel-arbor" },
    { id: "mainspring", name: "Mainspring", system: "Power", role: "Stores energy as elastic strain and meters it into the barrel across the power reserve.", lessonId: "power", lessonLabel: "Power", color: "#f0c879", kind: "mainspring", source: ["Mainspring_base"], sourceTransforms: { Mainspring_base: { position: [0.0295, -0.029, 0], rotation: [Math.PI, 0, 0] } }, home: [5.78, 2.89, 0.8], explode: [4.2, 2.7, 11], animation: "barrel-arbor" },
    { id: "barrel-bridge", name: "Barrel bridge", system: "Structure", role: "Supports the barrel arbor and the upper pivots of the winding train.", lessonId: "mainplate", lessonLabel: "Mainplate", color: "#9ba1a8", source: ["Barrel_bridge"], home: [3.3, 3.2, -0.8], explode: [3, 3, -7] },
    { id: "ratchet-wheel", name: "Ratchet wheel", system: "Winding", role: "Turns the barrel arbor during winding while the click blocks reverse rotation.", lessonId: "click", lessonLabel: "Click", color: "#c98c4a", source: ["Ratchet_wheel"], home: [5.78, 2.89, -1.2], explode: [4.8, 3.2, -10], animation: "barrel-arbor" },
    { id: "click", name: "Click", system: "Winding", role: "Locks the ratchet wheel one tooth at a time so stored energy cannot unwind through the crown.", lessonId: "click", lessonLabel: "Click", color: "#7fb069", source: ["Click"], home: [-3.2, 6.1, -1.1], explode: [-3.5, 4.4, -10], animation: "click" },
    { id: "click-spring", name: "Click spring", system: "Winding", role: "Keeps the click engaged while allowing it to ride over teeth during winding.", lessonId: "click", lessonLabel: "Click", color: "#91bd79", source: ["Click_spring"], home: [-1.4, 5.4, -1.05], explode: [-2.6, 4.9, -12], animation: "click-spring" },
    { id: "crown-wheel", name: "Crown wheel", system: "Winding", role: "Turns crown input through ninety degrees into torque at the ratchet wheel.", lessonId: "click", lessonLabel: "Winding", color: "#d0a05f", source: ["Crown_wheel"], home: [0.58, 6.98, -1.1], explode: [0.5, 5.5, -10], animation: "crown-wheel" },
    { id: "crown", name: "Crown", system: "Keyless works", role: "The user's external control for winding, date correction, and hand setting.", lessonId: "keyless-works", lessonLabel: "Keyless Works", color: "#7d899a", source: ["Crown"], home: [0, 10.6, 0.2], explode: [0, 7.5, 2] },
    { id: "winding-stem", name: "Winding stem", system: "Keyless works", role: "Carries crown rotation and axial pull into the movement.", lessonId: "keyless-works", lessonLabel: "Keyless Works", color: "#768397", source: ["Winding_stem"], home: [0, 9.7, 0.15], explode: [0, 8.5, 4] },
    { id: "winding-pinion", name: "Winding pinion", system: "Keyless works", role: "Transfers stem rotation into the winding train while remaining axially constrained.", lessonId: "keyless-works", lessonLabel: "Keyless Works", color: "#8795a8", source: ["Winding_pinion"], home: [-1.2, 8.8, 0.15], explode: [-1, 7.8, 6] },
    { id: "sliding-pinion", name: "Sliding pinion", system: "Keyless works", role: "Slides between winding and setting engagements as the crown changes position.", lessonId: "keyless-works", lessonLabel: "Keyless Works", color: "#8da1b5", source: ["Sliding_pinion"], home: [-2.4, 8.5, 0.2], explode: [-2.2, 7.1, 8] },
    { id: "yoke", name: "Yoke", system: "Keyless works", role: "Moves the sliding pinion between winding and hand-setting positions.", lessonId: "keyless-works", lessonLabel: "Keyless Works", color: "#87a7bd", source: ["Yoke"], home: [-5.7, 8.2, 0.35], explode: [-4.5, 6.5, 7] },
    { id: "setting-lever", name: "Setting lever", system: "Keyless works", role: "Indexes the stem's axial positions and redirects crown pull into the yoke.", lessonId: "keyless-works", lessonLabel: "Keyless Works", color: "#7395ad", source: ["Setting_lever"], home: [-4.4, 7.4, 0.3], explode: [-5.5, 5.7, 9] },
    { id: "setting-lever-jumper", name: "Setting lever jumper", system: "Keyless works", role: "Provides the detents felt at winding, date-setting, and time-setting positions.", lessonId: "keyless-works", lessonLabel: "Keyless Works", color: "#6e8da4", source: ["Setting_lever_jumper"], home: [-3.8, 6.6, 0.4], explode: [-6.2, 5, 11] },
    { id: "corrector-lever", name: "Corrector lever", system: "Keyless works", role: "Routes setting motion toward quick date correction when the stem is in its middle position.", lessonId: "keyless-works", lessonLabel: "Keyless Works", color: "#86a7b9", source: ["Corrector_lever"], home: [-2.1, 6.8, 0.55], explode: [-5.2, 4.4, 13] },
    { id: "stop-lever", name: "Stop lever", system: "Keyless works", role: "Halts the balance when the crown is pulled for precise time setting.", lessonId: "keyless-works", lessonLabel: "Keyless Works", color: "#9ab2c2", source: ["Stop_lever"], home: [-5.1, 4.8, 0.45], explode: [-6.8, 3.5, 12] },
    { id: "center-wheel", name: "Center wheel", system: "Gear train", role: "Receives barrel torque and begins the timed reduction toward the escapement.", lessonId: "gears", lessonLabel: "Gear Train", color: "#cbb47a", source: ["Second_wheel"], sourceTransforms: { Second_wheel: { position: [0, 0, 0], rotation: [0, 0, 0.0495] } }, home: [6.02, -4.14, 0.45], explode: [4.2, -3.2, 4], animation: "center" },
    { id: "center-pinion", name: "Center pinion", system: "Gear train", role: "The smaller pinion on the center wheel meshes with the barrel and sets the first train ratio.", lessonId: "gears", lessonLabel: "Gear Train", color: "#bca66e", kind: "gear", gear: [1.2, 17, 0.42, 0.34], home: [6.02, -4.14, 0.05], explode: [4.8, -3.8, 6], animation: "center" },
    { id: "third-wheel", name: "Third wheel", system: "Gear train", role: "Transfers power while stepping rotational speed upward and torque downward.", lessonId: "gears", lessonLabel: "Gear Train", color: "#b7c27a", source: ["Third_wheel"], sourceTransforms: { Third_wheel: { position: [0, 0, 0], rotation: [Math.PI, 0, 0.041] } }, home: [2.49, -2.77, 0.5], explode: [2, -3.4, 5], animation: "third" },
    { id: "third-pinion", name: "Third-wheel pinion", system: "Gear train", role: "The thirteen-leaf pinion receives the center wheel and drives the third wheel assembly.", lessonId: "gears", lessonLabel: "Gear Train", color: "#a8b36d", kind: "gear", gear: [0.95, 13, 0.4, 0.28], home: [2.49, -2.77, 0.1], explode: [2.4, -4.1, 7], animation: "third" },
    { id: "fourth-wheel", name: "Fourth wheel", system: "Gear train", role: "Completes one revolution per minute and commonly carries the seconds hand.", lessonId: "gears", lessonLabel: "Gear Train", color: "#86b989", source: ["Fourth_wheel"], sourceTransforms: { Fourth_wheel: { position: [0, 0, 0], rotation: [Math.PI, 0, 0.5] } }, home: [0, 0, 0.55], explode: [0, -2.5, 6], animation: "fourth" },
    { id: "fourth-pinion", name: "Fourth-wheel pinion", system: "Gear train", role: "The nine-leaf pinion receives the third wheel and fixes the fourth-wheel ratio.", lessonId: "gears", lessonLabel: "Gear Train", color: "#78aa7c", kind: "gear", gear: [0.78, 9, 0.4, 0.24], home: [0, 0, 0.12], explode: [0, -3.2, 8], animation: "fourth" },
    { id: "escape-wheel", name: "Escape wheel", system: "Escapement", role: "Meters train energy into discrete impulses delivered through the pallet fork.", lessonId: "escapement", lessonLabel: "Escapement", color: "#70b8c8", source: ["Escape_wheel"], sourceTransforms: { Escape_wheel: { position: [-0.0005, 0, 0], rotation: [0, 0, 0] } }, home: [-2.07, -3.03, 0.6], explode: [-2.2, -4.2, 7], animation: "escape" },
    { id: "escape-pinion", name: "Escape pinion", system: "Escapement", role: "The nine-leaf pinion receives the fourth wheel and carries the escape wheel.", lessonId: "escapement", lessonLabel: "Escapement", color: "#63a9ba", kind: "gear", gear: [0.72, 9, 0.38, 0.22], home: [-2.07, -3.03, 0.12], explode: [-2.8, -4.8, 9], animation: "escape" },
    { id: "train-bridge", name: "Train bridge", system: "Structure", role: "Captures the train pivots against the mainplate while preserving their center distances.", lessonId: "mainplate", lessonLabel: "Mainplate", color: "#9da5ad", source: ["Train_bridge"], home: [0.2, -3.5, -0.85], explode: [0, -5.2, -8] },
    { id: "cannon-pinion", name: "Cannon pinion", system: "Motion works", role: "Friction-fits to the center arbor, drives the minute hand, and permits manual setting.", lessonId: "motion-works", lessonLabel: "Motion Works", color: "#d2bc83", source: ["Cannon_pinion"], home: [0, 0, 1.05], explode: [1.5, 1.2, 8], animation: "cannon" },
    { id: "cannon-wheel", name: "Cannon wheel", system: "Motion works", role: "Carries center-wheel motion into the intermediate reduction that drives the hour wheel.", lessonId: "motion-works", lessonLabel: "Motion Works", color: "#c5ae75", source: ["Cannon_wheel"], home: [0, 0, 1.2], explode: [2, 1.8, 10], animation: "cannon" },
    { id: "hour-wheel", name: "Hour wheel", system: "Motion works", role: "Turns once per twelve hours around the cannon pinion and carries the hour hand.", lessonId: "motion-works", lessonLabel: "Motion Works", color: "#bba269", source: ["Hour_wheel"], home: [0, 0, 1.42], explode: [2.6, 2.4, 12], animation: "hour" },
    { id: "minute-train-bridge", name: "Minute-train bridge", system: "Structure", role: "Retains the motion works and calendar-side wheel pivots above the mainplate.", lessonId: "motion-works", lessonLabel: "Motion Works", color: "#a3abb2", source: ["Minute_train_bridge"], home: [-1.4, 3.8, 0.7], explode: [-1.5, 4.6, 9] },
    { id: "date-corrector", name: "Date corrector", system: "Calendar", role: "Advances the date ring directly during quick-set operation.", lessonId: "keyless-works", lessonLabel: "Keyless Works", color: "#9db5bf", source: ["Date_corrector"], home: [2.3, 6.87, 1.05], explode: [3.4, 5.2, 10] },
    { id: "date-indicator-spring", name: "Date indicator spring", system: "Calendar", role: "Loads the calendar driver so the date snaps cleanly between indexed positions.", lessonId: "motion-works", lessonLabel: "Motion Works", color: "#a7bdc4", source: ["Date_indicator_spring"], home: [-0.3, -4.2, 1.2], explode: [-1.2, -5.1, 11], animation: "date-spring" },
    { id: "date-jumper", name: "Date jumper", system: "Calendar", role: "Indexes the date ring and prevents it from resting between numerals.", lessonId: "motion-works", lessonLabel: "Motion Works", color: "#8faab5", source: ["Date_jumper"], home: [0.8, -6.26, 1.2], explode: [1.2, -5.8, 13], animation: "date-jumper" },
    { id: "date-jumper-plate", name: "Date-jumper plate", system: "Calendar", role: "Supports the jumper and calendar-driving reduction above the mainplate.", lessonId: "mainplate", lessonLabel: "Mainplate", color: "#a0aab2", source: ["Date_jumper_plate"], home: [0.2, -5.2, 0.9], explode: [0, -6.6, 10] },
    { id: "pallet-fork", name: "Pallet fork", system: "Escapement", role: "Alternately locks and releases the escape wheel, converting rotation into timed impulses.", lessonId: "escapement", lessonLabel: "Escapement", color: "#6bb7d6", source: ["Pallet_fork"], sourceTransforms: { Pallet_fork: { position: [-0.816784, 0.417752, 0], rotation: [Math.PI, 0, archivedPhase] } }, home: [-4.3, -1.33, 0.75], explode: [-4.2, -1.4, 9], animation: "pallet" },
    { id: "pallet-horn", name: "Pallet-fork horn", system: "Escapement", role: "Receives the balance roller jewel and transmits each impulse between balance and fork.", lessonId: "escapement", lessonLabel: "Escapement", color: "#79c4df", source: ["Pallet_fork_horn"], sourceTransforms: { Pallet_fork_horn: { position: [-1.639575, 1.247155, 0], rotation: [Math.PI, 0, archivedPhase] } }, home: [-4.3, -1.33, 0.86], explode: [-4.8, -1.8, 11], animation: "pallet" },
    { id: "entry-pallet-jewel", name: "Entry pallet jewel", system: "Escapement", role: "The first ruby locking face receives the approaching escape-wheel tooth.", lessonId: "escapement", lessonLabel: "Escapement", color: "#d95d78", source: ["Pallet_jewel_1"], sourceTransforms: { Pallet_jewel_1: { position: [1.13058, 0.885897, 0], rotation: [Math.PI, 0, archivedPhase] } }, transparent: true, home: [-4.3, -1.33, 0.95], explode: [-5.4, -2.2, 13], animation: "pallet" },
    { id: "exit-pallet-jewel", name: "Exit pallet jewel", system: "Escapement", role: "The second ruby locking face releases the escape wheel after the return impulse.", lessonId: "escapement", lessonLabel: "Escapement", color: "#e16b86", source: ["Pallet_jewel_2"], sourceTransforms: { Pallet_jewel_2: { position: [-0.578807, -1.512026, 0], rotation: [Math.PI, 0, archivedPhase] } }, transparent: true, home: [-4.3, -1.33, 1.02], explode: [-6, -2.6, 15], animation: "pallet" },
    { id: "pallet-bridge", name: "Pallet bridge", system: "Structure", role: "Captures the pallet staff while preserving the fork's narrow angular travel.", lessonId: "escapement", lessonLabel: "Escapement", color: "#9ca6ae", source: ["Pallet_bridge"], home: [-4.8, 0.4, -0.72], explode: [-5.2, 0.5, -8] },
    { id: "balance-wheel", name: "Balance wheel", system: "Regulator", role: "Oscillates with the hairspring to provide the movement's time base.", lessonId: "balance", lessonLabel: "Balance", color: "#c7a86b", source: ["Balance_wheel"], sourceTransforms: { Balance_wheel: { position: [0, 0, 0], rotation: [Math.PI, 0, archivedPhase] } }, home: [-6.54, 0.38, 0.65], explode: [-5.2, 1.4, 8], animation: "balance" },
    { id: "balance-staff", name: "Balance staff", system: "Regulator", role: "The fine central arbor carries the balance, roller, and impulse jewel between shock settings.", lessonId: "balance", lessonLabel: "Balance", color: "#b8a06e", kind: "shaft", shaft: [0.18, 2.3], source: ["Balance_shaft_end"], home: [-6.54, 0.38, 0.65], explode: [-5.8, 1.8, 10], animation: "balance" },
    { id: "safety-roller", name: "Safety roller", system: "Regulator", role: "Prevents accidental fork unlocking and carries the impulse interface beneath the balance.", lessonId: "balance", lessonLabel: "Balance", color: "#b99e66", source: ["Balance_safety", "Balance_spring_base"], home: [-6.54, 0.38, 0.4], explode: [-6.4, 2.2, 12], animation: "balance" },
    { id: "hairspring", name: "Hairspring", system: "Regulator", role: "Returns the balance toward center; its elastic rate and active length determine the beat.", lessonId: "balance", lessonLabel: "Balance", color: "#9ed0d8", kind: "hairspring", home: [-6.54, 0.38, 1], explode: [-7, 2.6, 14], animation: "hairspring" },
    { id: "balance-bridge", name: "Balance bridge", system: "Structure", role: "Supports the upper balance pivot and carries the regulator and stud holder.", lessonId: "balance", lessonLabel: "Balance", color: "#9ba1a8", source: ["Balance_bridge"], home: [-6.2, 2.8, -0.75], explode: [-6.4, 3.6, -8] },
    { id: "lower-index", name: "Regulator index", system: "Regulator", role: "Changes the hairspring's effective active length to adjust rate.", lessonId: "balance", lessonLabel: "Balance", color: "#91a6b1", source: ["Lower_index"], home: [-6.1, 2.2, -0.42], explode: [-7.2, 4.1, -6] },
    { id: "upper-index", name: "Index cap", system: "Regulator", role: "Retains the hairspring at the regulator pins while allowing controlled adjustment.", lessonId: "balance", lessonLabel: "Balance", color: "#9cafb8", source: ["Upper_index"], home: [-6, 2.1, -0.3], explode: [-7.8, 4.6, -4] },
    { id: "stud-base", name: "Hairspring stud carrier", system: "Regulator", role: "Positions the fixed outer end of the hairspring relative to the balance bridge.", lessonId: "balance", lessonLabel: "Balance", color: "#8da2ad", source: ["Stud_base"], home: [-7, 2.9, -0.35], explode: [-8.4, 5.1, -2] },
    { id: "hairspring-stud", name: "Hairspring stud", system: "Regulator", role: "Clamps the hairspring's outer terminal so the coil can develop restoring torque.", lessonId: "balance", lessonLabel: "Balance", color: "#a2b2ba", source: ["Stud"], home: [-7.2, 2.7, -0.2], explode: [-9, 5.6, 0] },
    { id: "balance-jewel", name: "Balance jewel", system: "Friction", role: "Supports the high-speed balance pivot with a hard, low-friction ruby bearing.", lessonId: "mainplate", lessonLabel: "Jewel Bearings", color: "#dc5574", source: ["Balance_jewel"], transparent: true, home: [-6.54, 0.38, 0.2], explode: [-7.2, 0.5, 10] },
    { id: "shock-setting", name: "Shock setting", system: "Shock protection", role: "Allows the balance cap jewel to move under impact and return concentrically.", lessonId: "balance", lessonLabel: "Balance", color: "#8899a6", source: ["Shock_base", "Shock_center"], home: [-6.54, 0.38, -0.25], explode: [-7.8, 0.1, -7] },
    { id: "shock-jewel", name: "Shock cap jewel", system: "Shock protection", role: "Controls balance endshake and spreads axial impact into the spring-loaded setting.", lessonId: "balance", lessonLabel: "Balance", color: "#e06382", source: ["Shock_jewel"], transparent: true, home: [-6.54, 0.38, -0.4], explode: [-8.4, -0.4, -9] },
    { id: "shock-spring", name: "Shock spring", system: "Shock protection", role: "Retains the cap jewel while permitting temporary movement under shock.", lessonId: "balance", lessonLabel: "Balance", color: "#aeb8bf", source: ["Shock_spring"], home: [-6.54, 0.38, -0.5], explode: [-9, -0.9, -11] },
    { id: "mainplate-jewels", name: "Mainplate jewels", system: "Friction", role: "Ruby bearings locate the train's lower pivots with low wear and controlled oil wells.", lessonId: "mainplate", lessonLabel: "Jewel Bearings", color: "#d95d78", kind: "jewels", source: ["Jewel_bearing"], transparent: true, instances: [[5.78, 2.89, 0.35], [6.02, -4.14, 0.35], [2.49, -2.77, 0.35], [0, 0, 0.35], [-2.07, -3.03, 0.35], [-4.3, -1.33, 0.35]], home: [0, 0, 0], explode: [0, 0, 7] },
    { id: "bridge-jewels", name: "Bridge jewels", system: "Friction", role: "Upper train jewels complete each pivot pair and maintain arbor alignment under load.", lessonId: "mainplate", lessonLabel: "Jewel Bearings", color: "#e36a86", kind: "jewels", source: ["Jewel_pretty"], transparent: true, instances: [[6.02, -4.14, -0.5], [2.49, -2.77, -0.5], [0, 0, -0.5], [-2.07, -3.03, -0.5], [-4.3, -1.33, -0.5]], home: [0, 0, 0], explode: [0, -1, -7] },
    { id: "rotor", name: "Automatic rotor", system: "Automatic winding", role: "The weighted rotor harvests wrist motion and drives the reversers in either direction.", lessonId: "automatic-winding", lessonLabel: "Automatic Winding", color: "#676d78", source: ["Weight"], home: [0, 0, -1.8], explode: [0, 0, -16], animation: "rotor" },
    { id: "reverser-a", name: "Reversing wheel A", system: "Automatic winding", role: "Locks and slips according to rotor direction so one sense of motion reaches the winding train.", lessonId: "automatic-winding", lessonLabel: "Automatic Winding", color: "#7991c8", source: ["Reversing_wheel_top", "Reversing_wheel_bottom", "Reversing_wheel_lever"], home: [-3.29, -3.19, -1.25], explode: [-3.2, -3.6, -12], animation: "reverser-a" },
    { id: "reverser-b", name: "Reversing wheel B", system: "Automatic winding", role: "Complements the first reverser so clockwise or counterclockwise rotor travel can wind the barrel.", lessonId: "automatic-winding", lessonLabel: "Automatic Winding", color: "#6f89c0", source: ["Reversing_wheel_top", "Reversing_wheel_bottom", "Reversing_wheel_cut", "Reversing_wheel_lever"], home: [0.75, -4.52, -1.25], explode: [0.8, -4.6, -14], animation: "reverser-b" },
    { id: "auto-framework", name: "Automatic framework", system: "Automatic winding", role: "Locates the reversers and reduction wheels on the movement side.", lessonId: "automatic-winding", lessonLabel: "Automatic Winding", color: "#8c969f", source: ["Automatic_device_framework"], home: [0, -1.2, -1.5], explode: [-1.2, -2.2, -11] },
    { id: "auto-bridge", name: "Automatic bridge", system: "Automatic winding", role: "Closes the automatic winding module and supports its upper pivots.", lessonId: "automatic-winding", lessonLabel: "Automatic Winding", color: "#9ca5ac", source: ["Automatic_device_bridge"], home: [0, -1.2, -1.7], explode: [1.2, -2.8, -13] },
    { id: "auto-train", name: "Automatic reduction train", system: "Automatic winding", role: "Two generated compound gears reduce rotor motion and deliver winding torque to the barrel.", lessonId: "automatic-winding", lessonLabel: "Automatic Winding", color: "#8fa7cf", kind: "automatic-gears", home: [4.1, -2.6, -1.35], explode: [3.6, -3.6, -15], animation: "automatic-train" },
    { id: "movement-screws", name: "Movement screws", system: "Hardware", role: "Scaled source screw heads and generated shafts clamp bridges and modules without disturbing pivot alignment.", lessonId: "mainplate", lessonLabel: "Assembly", color: "#a9b0b6", kind: "screws", source: ["Screw_head"], home: [0, 0, 0], explode: [0, 0, -18] },
  ];

  window.WATCH_EXPLORER = Object.freeze({
    lessons: Object.freeze(lessons.map((lesson) => Object.freeze(lesson))),
    modelRanges: Object.freeze(modelRanges),
    parts: Object.freeze(parts.map((part) => Object.freeze(part))),
  });
})();
